---

# Playbook install FreeIPA Client
- name: Playbook Configure IPA Clients with username / password
  hosts: localhost
  become: true

  tasks:
    - name: Install Epel-Release
      become: true
      yum:
        name: epel-release
        state: latest
    - name: Install Firewalld
      become: true
      yum:
        name: firewalld
        state: latest
    - name: Disable SElinux
      selinux:
        state: disabled
    - name: install bind9
      yum:
        name: bind-utils
        state: latest
    - name: install IPA client Package
      yum:
        name: freeipa-client
        state: latest
    - name: Configure IPA Client 
      shell: ipa-client-install --server=yourfreeipa-server.com --domain=yourdomain.com --realm=YOUR-REALM.COM --principal=admin --password=your-password --mkhomedir --force-ntpd --unattended
    - name: permit traffic in default zone for freeipa service
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
       - http
       - https
       - dns
       - ntp
       - freeipa-ldap
       - freeipa-ldaps
    - name: Reload config Firewall
      become: true
      shell: firewall-cmd --reload
